site_name: PUMA

extra_css: 
    - assets/stylesheets/extra.css

theme:
    name: material
    language: pt
    features:
        - navigation.tabs

nav:
    - Home: index.md
    - Projeto:
        - Quadro de Conhecimento: projeto/quadro_de_conhecimento.md
        - Plano de comunicação: projeto/quadro_de_disponibilidade.md
        - Plano de contribuição: projeto/plano_de_contribuicao.md
    - Sprints:
        - Sprint 0:
            - Planning sprint 0: sprints/sprint0/planning.md
        - Sprint 1:
            - Planning sprint 1: sprints/sprint1/planning.md
        - Sprint 2:
            - Planning sprint 2: sprints/sprint2/planning.md
