site_name: PUMA

extra_css: 
    - assets/stylesheets/extra.css

theme:
    name: material
    language: pt
    features:
        - navigation.tabs

nav:
    - Home: index.md
    - Produto: 
        - Documento de Visão: produto/documento_visao.md
        - Protótipo de Alta Fidelidade: produto/prototipo_de_alta.md
    - Projeto:
        - Quadro de Conhecimento: projeto/quadro_de_conhecimento.md
        - Plano de comunicação: projeto/quadro_de_disponibilidade.md
        - Plano de gerenciamento de riscos: projeto/plano_de_gerenciamento_de_riscos.md
        - Plano de custos: projeto/plano_de_custos.md
    - Sprints:
        - Sprint 0:
            - Planning sprint 0: sprints/sprint0/planning.md
        - Sprint 1:
            - Planning sprint 1: sprints/sprint1/planning.md
        - Sprint 2:
            - Planning sprint 2: sprints/sprint2/planning.md
