site_name: PUMA

extra_css: 
    - assets/stylesheets/extra.css

theme:
    name: material
    language: pt
    features:
        - navigation.tabs

nav:
    - Home: index.md
    - Projeto:
        - Quadro de Disponilidade: projeto/quadro_de_disponibilidade.md
    - Sprints:
        - Sprint 1:
            - Planning sprint 1: sprints/sprint1/planning.md
        - Sprint 0:
            - Planning sprint 0: sprints/sprint0/planning.md