site_name: PUMA

extra_css: 
    - assets/stylesheets/extra.css

theme:
    name: material
    language: pt
    features:
        - navigation.tabs

nav:
    - Home: index.md
    - Produto:
        - Visão do produto: produto/documento_visao.md
        - Documento de Arquitetura: produto/doc_arquitetura.md
        - Protótipo de Alta Fidelidade: produto/prototipo_de_alta.md
    - Projeto:
        - Quadro de Conhecimento: projeto/quadro_de_conhecimento.md
        - Plano de comunicação: projeto/quadro_de_disponibilidade.md
        - Plano de contribuição: projeto/plano_de_contribuicao.md
        - Plano de gerenciamento de riscos: projeto/plano_de_gerenciamento_de_riscos.md
        - Plano de custos: projeto/plano_de_custos.md
        - Metodologia: projeto/metodologia.md
        - Estrutura Analítica do Projeto: projeto/eap.md
        - Roadmap: projeto/roadmap.md
    - Gestão do projeto:
        - Semana 0:
            - Planning: sprints/sprint0/planning.md
        - Semana 1:
            - Planning: sprints/sprint1/planning.md
        - Semana 2:
            - Planning: sprints/sprint2/planning.md
        - Semana 3:
            - Planning: sprints/sprint3/planning.md
            - Review: sprints/sprint3/review.md
        - Semana 4:
            - Planning: sprints/sprint4/planning.md
            - Review: sprints/sprint4/review.md
        - Semana 5:
            - Planning: sprints/sprint5/planning.md
