site_name: PUMA

extra_css: 
    - assets/stylesheets/extra.css

theme:
    name: material
    language: pt
    features:
        - navigation.tabs

nav:
    - Home: index.md
    - Produto:
        - Visão do produto: produto/documento_visao.md
        - Documento de Arquitetura: produto/doc_arquitetura.md
        - Protótipo de Alta Fidelidade: produto/prototipo_de_alta.md
    - Projeto:
        - Quadro de Conhecimento: projeto/quadro_de_conhecimento.md
        - Plano de comunicação: projeto/quadro_de_disponibilidade.md
        - Plano de contribuição: projeto/plano_de_contribuicao.md
        - Plano de gerenciamento de riscos: projeto/plano_de_gerenciamento_de_riscos.md
        - Plano de custos: projeto/plano_de_custos.md
        - Metodologia: projeto/metodologia.md
        - Estrutura Analítica do Projeto: projeto/eap.md
        - Roadmap: projeto/roadmap.md
    - Sprints:
        - Sprint 0:
            - Planning sprint 0: sprints/sprint0/planning.md
        - Sprint 1:
            - Planning sprint 1: sprints/sprint1/planning.md
        - Sprint 2:
            - Planning sprint 2: sprints/sprint2/planning.md
        - Sprint 3:
            - Planning sprint 3: sprints/sprint3/planning.md
            - Review sprint 3: sprints/sprint3/review.md
        - Sprint 4:
            - Planning sprint 4: sprints/sprint4/planning.md
            - Review sprint 4: sprints/sprint4/review.md
        - Sprint 5:
            - Planning sprint 5: sprints/sprint5/planning.md
            - Review sprint 5: sprints/sprint5/review.md
        - Sprint 6:
            - Planning sprint 6: sprints/sprint6/planning.md
