site_name: PUMA

extra_css: 
    - assets/stylesheets/extra.css

theme:
    name: material
    language: pt
    features:
        - navigation.tabs

nav:
    - Home: index.md
    - Sprints:
        - Sprint 1:
            - Planning sprint 1: sprints/sprints1/planning.md