site_name: PUMA

extra_css: 
    - assets/stylesheets/extra.css

theme:
    name: material
    language: pt
    features:
        - navigation.tabs

nav:
    - Home: index.md
    - Produto:
        - Visão do Produto: produto/documento_visao.md
        - Documento de Arquitetura: produto/doc_arquitetura.md
        - Protótipo de Alta Fidelidade: produto/prototipo_de_alta.md
        - Backlog Inicial do Produto: produto/backlog_inicial_produto.md
    - Projeto:
        - Quadro de Conhecimento: projeto/quadro_de_conhecimento.md
        - Plano de Comunicação: projeto/quadro_de_disponibilidade.md
        - Plano de Contribuição: projeto/plano_de_contribuicao.md
        - Plano de Gerenciamento de Riscos: projeto/plano_de_gerenciamento_de_riscos.md
        - Plano de Custos: projeto/plano_de_custos.md
        - Metodologia: projeto/metodologia.md
        - Estrutura Analítica do Projeto: projeto/eap.md
        - Roadmap: projeto/roadmap.md
    - Gestão do Projeto:
        - Semana 0:
            - Planning: semanas/semana0/planning.md
        - Semana 1:
            - Planning: semanas/semana1/planning.md
        - Semana 2:
            - Planning: semanas/semana2/planning.md
        - Semana 3:
            - Planning: semanas/semana3/planning.md
            - Review: semanas/semana3/review.md
        - Semana 4:
            - Planning: semanas/semana4/planning.md
            - Review: semanas/semana4/review.md
        - Semana 5:
            - Planning: semanas/semana5/planning.md
            - Review: semanas/semana5/review.md
        - Semana 6:
            - Planning: semanas/semana6/planning.md
            - Review: semanas/semana6/review.md

