name: Generate Metrics Release

on:
  repository_dispatch:
    types: [event_name]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          pip3 install requests && python3 metrics_file.py ${{github.event.client_payload.repo_name}} ${{github.event.client_payload.version}}
          git add .
          git commit -m "Gerando métricas SonarCloud ${{github.event.client_payload.repo_name}} v${{github.event.client_payload.version}}"
          git push
          echo "Metrics File Generated Successfully."